"""initial_schema

Revision ID: 7929718f7fb9
Revises: 
Create Date: 2026-05-13 20:49:14.269228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '7929718f7fb9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    

    op.create_table('medical_knowledge',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("""
        
        CREATE INDEX idx_knowledge_embedding ON medical_knowledge
        USING hnsw (embedding vector_cosine_ops)
        WITH(m= 16, ef_construction = 64)

    """)
    op.create_index('idx_knowledge_category', 'medical_knowledge', ['category'], unique=False)
    op.create_table('otp_tokens',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('token', sa.String(length=6), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_otp_phone_purpose', 'otp_tokens', ['phone', 'purpose'], unique=False, postgresql_where=sa.text('NOT used'))
    op.create_table('patients',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('openmrs_patient_id', sa.String(length=50), nullable=False),
    sa.Column('whatsapp_phone', sa.String(length=20), nullable=True),
    sa.Column('web_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'pending_channel_link'"), nullable=False),
    sa.Column('preferred_channel', sa.String(length=10), server_default=sa.text("'whatsapp'"), nullable=True),
    sa.Column('language', sa.String(length=10), server_default=sa.text("'en'"), nullable=True),
    sa.Column('preferred_doctor_id', sa.String(length=50), nullable=True),
    sa.Column('reminder_lead_days', postgresql.ARRAY(sa.Integer()), server_default=sa.text("'{7,1}'::integer[]"), nullable=True),
    sa.Column('reminder_lead_hours', postgresql.ARRAY(sa.Integer()), server_default=sa.text("'{2}'::integer[]"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openmrs_patient_id'),
    sa.UniqueConstraint('web_email'),
    sa.UniqueConstraint('whatsapp_phone')
    )
    op.create_table('appointment_records',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('openmrs_appt_id', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=20), server_default=sa.text("'agent'"), nullable=False),
    sa.Column('doctor_name', sa.String(length=100), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'scheduled'"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openmrs_appt_id')
    )
    op.create_index('idx_appts_patient', 'appointment_records', ['patient_id'], unique=False)
    op.create_index('idx_appts_scheduled', 'appointment_records', ['scheduled_at'], unique=False)
    op.create_table('conversation_sessions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('thread_id', sa.String(length=100), nullable=False),
    sa.Column('current_flow', sa.String(length=30), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_index('idx_sessions_patient_channel', 'conversation_sessions', ['patient_id', 'channel'], unique=False)
    op.create_table('report_delivery_log',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('openmrs_resource_id', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=30), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('delivery_status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('ai_explanation_summary', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('patient_acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'openmrs_resource_id', name='uq_report_patient_resource')
    )
    op.create_table('reminder_schedules',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('trigger_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('template_name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_status', sa.String(length=20), nullable=True),
    sa.Column('message_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment_records.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reminders_patient', 'reminder_schedules', ['patient_id'], unique=False)
    op.create_index('idx_reminders_trigger', 'reminder_schedules', ['trigger_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP EXTENSION IF EXISTS vector")

    op.drop_index('idx_reminders_trigger', table_name='reminder_schedules', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('idx_reminders_patient', table_name='reminder_schedules')
    op.drop_table('reminder_schedules')
    op.drop_table('report_delivery_log')
    op.drop_index('idx_sessions_patient_channel', table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    op.drop_index('idx_appts_scheduled', table_name='appointment_records')
    op.drop_index('idx_appts_patient', table_name='appointment_records')
    op.drop_table('appointment_records')
    op.drop_table('patients')
    op.drop_index('idx_otp_phone_purpose', table_name='otp_tokens', postgresql_where=sa.text('NOT used'))
    op.drop_table('otp_tokens')
    op.drop_index('idx_knowledge_category', table_name='medical_knowledge')
    op.drop_table('medical_knowledge')
    # ### end Alembic commands ###
